### PR TITLE
Auto-copy URL for newly opened PR

### LINKED ISSUE #17: Auto-pbcopy pull request URL with `hub pull-request`
`hub pull-request` pops open Vim, prints out some debugging git output, then prints the GitHub PR URL. I want to copy that URL.

`hub pull-request | pbcopy` doesn't work, because Vim really doesn't like being piped to another process.

One idea:

```bash
$ vim /tmp/commitmsg && hub pull-request -m $(cat /tmp/commitmsg) | pbcopy
$ rm /tmp/commitmsg
```

Wrinkle:

`hub pull-request` shows a helpful commit message template that includes commit messages since master. I'd like to keep that. It uses [this code](https://github.com/github/hub/blob/0900df0104e2422180b6377e471b2a320730f13c/commands/pull_request.go#L238-L261) to do that.

According to [the `git.Log()` code](https://github.com/github/hub/blob/0900df0104e2422180b6377e471b2a320730f13c/git/git.go#L141-L155), this should replicate that template:

```
git log --format="%h (%aN, %ar)%n%w(78,3,3)%s%n%+b" | sed 's/^/# /'
```

### PR DESCRIPTION
**Pull request by gabebw**
This lets me use Vim to write the commit message with all of the commits shown (just like `hub pull-request`) but still get the URL of the pull request automatically copied.

Fixes #17.

Thanks @gfontenot!

### CODE REVIEW

**Comment by gabebw** [comment]
@gfontenot Do you know why GitHub keeps the lines `# like this` as H1s instead of stripping them out?

**Comment by gabebw** [comment]
Oh because I'm passing the raw message to `hub pull-request -m`. Fixed now, I think.

**Comment by gabebw** [comment]
Gordon's version: https://github.com/gfontenot/dotfiles/pull/19

**Comment by gfontenot** [comment]
I've updated my version with some More Smarts if you're interested in checking it out.

**Pull request merged**
